### ISSUE TITLE
Jenkins提交项目配置Pipeline中文乱码

### ISSUE THREAD

**Issue by yoyofx** [go-atomci/workflow#1]
提交项目时，生成的 pipeline dsl 如果有中文信息会出现乱码的情况；

应该是 sentHTTPRequest 函数中未指定Post的编码编码格式。

**Comment by yoyofx** [comment]
已提交PR

**Comment by colynn** [comment]
thanks @yoyofx

**Comment by yoyofx** [comment]
@colynn 加你微信，没回复
